apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice.fullname" . }}
  labels:
    app: {{ include "microservice.fullname" . }}
spec:
  type: {{ .Values.serviceType }}
  selector:
    app: {{ include "microservice.fullname" . }}
  ports:
    - protocol: TCP
      port: http
      targetPort: http