apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice.fullname" . }}
  labels:
    {{- include "microservice.selectorLabels" . | nindent 4 }}
    app: {{ .Values.nameOverride }}
spec:
  type: ClusterIP
  selector:
    {{- include "microservice.selectorLabels" . | nindent 4 }}
    app: { { .Values.nameOverride } }
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080